import React, { useState } from 'react';
import { generateSolarVisualization } from '../services/gemini';
import { Sparkles, Loader2, Image as ImageIcon } from 'lucide-react';

const SolarVisualizer: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt) return;
    
    setIsLoading(true);
    setError(null);
    setImageUrl(null);

    try {
      const result = await generateSolarVisualization(prompt);
      if (result) {
        setImageUrl(result);
      } else {
        // If API Key is missing or generation fails silently
        if (!process.env.API_KEY) {
           setError("API Key missing. Please provide a valid API Key to use this feature.");
        } else {
           setError("Failed to generate image. Please try a different description.");
        }
      }
    } catch (err) {
      setError("An unexpected error occurred.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-slate-100">
      <div className="p-8">
        <div className="flex items-center gap-2 mb-4">
            <Sparkles className="w-5 h-5 text-solar-500" />
            <h3 className="text-xl font-bold text-slate-900">Visualize Your Solar Future</h3>
        </div>
        <p className="text-slate-600 mb-6 text-sm">
          Describe your home (e.g., "Modern suburban house with tiled roof in Cape Town"), and our AI will visualize a solar installation for you.
        </p>
        
        <div className="flex gap-2 flex-col sm:flex-row mb-6">
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="E.g. Double story house with terracotta roof tiles..."
            className="flex-1 px-4 py-3 rounded-lg border border-slate-300 focus:ring-2 focus:ring-solar-500 focus:border-solar-500 outline-none transition-all"
          />
          <button
            onClick={handleGenerate}
            disabled={isLoading || !prompt}
            className="bg-solar-600 hover:bg-solar-700 disabled:bg-slate-300 disabled:cursor-not-allowed text-white px-6 py-3 rounded-lg font-semibold transition-all flex items-center justify-center gap-2 min-w-[140px]"
          >
            {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
            Generate
          </button>
        </div>

        {error && (
            <div className="p-4 bg-red-50 text-red-600 rounded-lg text-sm mb-4">
                {error}
            </div>
        )}

        <div className="relative aspect-video bg-slate-100 rounded-lg overflow-hidden flex items-center justify-center border-2 border-dashed border-slate-200">
          {isLoading ? (
            <div className="flex flex-col items-center gap-3 text-slate-400 animate-pulse">
                <Loader2 className="w-10 h-10 animate-spin" />
                <span className="text-sm font-medium">Designing your system...</span>
            </div>
          ) : imageUrl ? (
            <img src={imageUrl} alt="AI Generated Solar Visualization" className="w-full h-full object-cover" />
          ) : (
            <div className="flex flex-col items-center gap-2 text-slate-400">
                <ImageIcon className="w-10 h-10" />
                <span className="text-sm">Preview will appear here</span>
            </div>
          )}
        </div>
        <p className="mt-2 text-xs text-slate-400 text-center italic">
            * Images are generated by AI for visualization purposes only. Actual installation may vary.
        </p>
      </div>
    </div>
  );
};

export default SolarVisualizer;